CREATE PROCEDURE sp_UpdateUserProfile
    @Id INT,
    @UserId INT,
    @FullName NVARCHAR(200),
    @Email NVARCHAR(200),
    @Phone NVARCHAR(50),
    @Bio NVARCHAR(500) = NULL,
    @Description NVARCHAR(MAX) = NULL,
    @IsActive BIT,
    @LinkedIn NVARCHAR(500) = NULL,
    @GitHub NVARCHAR(500) = NULL,
    @LeetCode NVARCHAR(500) = NULL,
    @University NVARCHAR(200) = NULL,
    @Degree NVARCHAR(200) = NULL,
    @Department NVARCHAR(200) = NULL,
    @GraduationYear INT = NULL,
    @GPA NVARCHAR(50) = NULL,
    @CompanyName NVARCHAR(200) = NULL,
    @Position NVARCHAR(200) = NULL,
    @ExperienceFrom DATETIME = NULL,
    @ExperienceTo DATETIME = NULL,
    @TotalExperience NVARCHAR(50) = NULL,
    @NoticePeriod NVARCHAR(50) = NULL,
    @ProfileImage NVARCHAR(500) = NULL,
    @ResumeFile NVARCHAR(500) = NULL,
    @ResumeUrl NVARCHAR(500) = NULL,
    @UpdatedAt DATETIME
AS
BEGIN
    UPDATE UserProfiles
    SET
        UserId = @UserId,
        FullName = @FullName,
        Email = @Email,
        Phone = @Phone,
        Bio = @Bio,
        Description = @Description,
        IsActive = @IsActive,
        LinkedIn = @LinkedIn,
        GitHub = @GitHub,
        LeetCode = @LeetCode,
        University = @University,
        Degree = @Degree,
        Department = @Department,
        GraduationYear = @GraduationYear,
        GPA = @GPA,
        CompanyName = @CompanyName,
        Position = @Position,
        ExperienceFrom = @ExperienceFrom,
        ExperienceTo = @ExperienceTo,
        TotalExperience = @TotalExperience,
        NoticePeriod = @NoticePeriod,
        ProfileImage = @ProfileImage,
        ResumeFile = @ResumeFile,
        ResumeUrl = @ResumeUrl,
        UpdatedAt = @UpdatedAt
    WHERE Id = @Id;
END
