CREATE TABLE [dbo].[ApplyJobs] (
    [Id]              INT            IDENTITY (1, 1) NOT NULL,
    [JobId]           INT            NOT NULL,
    [JobTitle]        NVARCHAR (MAX) NOT NULL,
    [JobType]         NVARCHAR (MAX) NOT NULL,
    [FullName]        NVARCHAR (MAX) NOT NULL,
    [Email]           NVARCHAR (MAX) NOT NULL,
    [Phone]           NVARCHAR (MAX) NOT NULL,
    [ResumeUrl]       NVARCHAR (MAX) NULL,
    [ResumeFile]      NVARCHAR (MAX) NULL,
    [University]      NVARCHAR (MAX) NOT NULL,
    [Degree]          NVARCHAR (MAX) NOT NULL,
    [Department]      NVARCHAR (MAX) NOT NULL,
    [GPA]             NVARCHAR (MAX) NOT NULL,
    [GraduationYear]  INT            NOT NULL,
    [CompanyName]     NVARCHAR (MAX) NULL,
    [Position]        NVARCHAR (MAX) NULL,
    [TotalExperience] NVARCHAR (MAX) NULL,
    [NoticePeriod]    NVARCHAR (MAX) NULL,
    [ExperienceFrom]  DATETIME2 (7)  NULL,
    [ExperienceTo]    DATETIME2 (7)  NULL,
    [LinkedIn]        NVARCHAR (MAX) NULL,
    [GitHub]          NVARCHAR (MAX) NULL,
    [AppliedDate]     DATETIME2 (7)  NOT NULL,
    [UserId]          INT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ApplyJobs] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_User_Job] UNIQUE NONCLUSTERED ([UserId] ASC, [JobId] ASC)
);

