CREATE TABLE [dbo].[UserProfiles] (
    [Id]              INT            IDENTITY (1, 1) NOT NULL,
    [UserId]          INT            NOT NULL,
    [FullName]        NVARCHAR (MAX) NOT NULL,
    [Email]           NVARCHAR (MAX) NOT NULL,
    [Phone]           NVARCHAR (MAX) NOT NULL,
    [Bio]             NVARCHAR (MAX) NULL,
    [Description]     NVARCHAR (MAX) NULL,
    [IsActive]        BIT            NOT NULL,
    [LinkedIn]        NVARCHAR (MAX) NULL,
    [GitHub]          NVARCHAR (MAX) NULL,
    [LeetCode]        NVARCHAR (MAX) NULL,
    [CompanyName]     NVARCHAR (MAX) NULL,
    [Position]        NVARCHAR (MAX) NULL,
    [ExperienceFrom]  DATETIME2 (7)  NULL,
    [ExperienceTo]    DATETIME2 (7)  NULL,
    [TotalExperience] NVARCHAR (MAX) NULL,
    [NoticePeriod]    NVARCHAR (MAX) NULL,
    [ProfileImage]    NVARCHAR (MAX) NULL,
    [ResumeFile]      NVARCHAR (MAX) NULL,
    [ResumeUrl]       NVARCHAR (MAX) NULL,
    [CreatedAt]       DATETIME2 (7)  NOT NULL,
    [UpdatedAt]       DATETIME2 (7)  NULL,
    [Degree]          NVARCHAR (MAX) NULL,
    [Department]      NVARCHAR (MAX) NULL,
    [GPA]             NVARCHAR (MAX) NULL,
    [GraduationYear]  INT            NULL,
    [University]      NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_UserProfiles] PRIMARY KEY CLUSTERED ([Id] ASC)
);

